### ISSUE TITLE
[feature] the ability to opt a controller out of sync from commands 

### ISSUE THREAD

**Issue by caleygoff-invitae** [simap/Firestorm#51]
It might be useful to have the ability to opt a controller in Firestorm to not send commands to.  I could see this being implemented by selecting the controller in firestorm and then having the .map() in the send command object ignore the selected Pixelblaze ids. The UI could either present checkboxes or a button that is labeled enable or disable depending on the state of the controller saved in the db instance of the firestorm server.

For my use case I have an art peace with two Pixelblaze controllers attached to it, a pico and a PB standard. Essentially the pico runs a border of 345 a led string that looks really good on a particular pattern that is different than what the other PB is running over 500 LEDs in the center. 

Presently both strands are synced together if firestorm is running in a network which for some might be undesirable.

**Comment by simap** [comment]
deleting from wrong account
